server:
  servlet:
    context-path: /heromanager

spring:
 datasource:
    url: jdbc:mysql://${DB_HOST}:3306/herodb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

management:
 endpoint:
   env:
     show-values: always