spring:
  datasource:
    url: jdbc:h2:mem:herodb
    driver-class-name: org.h2.Driver
    username: sa
    password:

h2:
  console:
    enabled: true
    path: /h2

auth:
  enabled: true


logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          cors: DEBUG
