apiVersion: v1
kind: ConfigMap
metadata:
  name: heromanager-config
  namespace: herospace
data:
    DB_HOST: herodb 
    DB_PORT: "3306"
    REDIS_HOST: redis
    REDIS_PORT: "6379"
    REDIS_PASSWORD: ""
    AUTH_SRV_HOST: http://authserver
    AUTH_SRV_PORT: "8081"